export const CHANGE_TOP_BANNERS = "CHANGE_TOP_BANNERS";
export const CHANGE_HOT_RECOMMEND = "CHANGE_HOT_RECOMMEND";
export const CHANGE_NEW_ALBUMS = "CHANGE_NEW_ALBUMS";
export const CHANGE_SURGE_RANK = "CHANGE_SURGE_RANK";
export const CHANGE_NEW_RANK = "CHANGE_NEW_RANK";
export const CHANGE_ORIGINAL_RANK = "CHANGE_ORIGINAL_RANK";