export const CHANGE_MUSIC_DETAIL = "CHANGE_MUSIC_DETAIL";
export const CHANGE_CURRENT_PANEL = "CHANGE_CURRENT_PANEL";
export const CHANGE_MUSIC_LYRIC = "CHANGE_MUSIC_LYRIC";
export const CHANGE_MUSIC_COMMENT = "CHANGE_MUSIC_COMMENT";
export const CHANGE_SIMILAR_MUSIC = "CHANGE_SIMILAR_MUSIC";
