export const CHANGE_ARTIST_TOP = "CHANGE_ARTIST_TOP";
export const CHANGE_ARTIST_ALBUM = "CHANGE_ARTIST_ALBUM";
export const CHANGE_ARTIST_MV = "CHANGE_ARTIST_MV";
export const CHANGE_ARTIST_DESC = "CHANGE_ARTIST_DESC";
